name: Build

on:
  push:
    branches: [main]
  pull_request: {}
  merge_group: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        repository: diasurgical/devilutionX
        path: devilutionX
        fetch-depth: 0

    - name: Create Build Environment
      shell: bash
      run: |
        cd devilutionX
        sudo apt-get update
        sudo apt-get install -y cmake gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 pkg-config-mingw-w64-x86-64 libz-mingw-w64-dev gettext dpkg-dev wget git sudo smpq
        sudo rm /usr/x86_64-w64-mingw32/lib/libz.dll.a
        sudo Packaging/windows/mingw-prep64.sh
        cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=OFF -DCPACK=ON -DCMAKE_TOOLCHAIN_FILE=../CMake/platforms/mingwcc64.toolchain.cmake -DDEVILUTIONX_SYSTEM_BZIP2=OFF -DDEVILUTIONX_STATIC_LIBSODIUM=ON -DDISCORD_INTEGRATION=ON
        cmake --build build -j $(nproc) --target package
        mkdir -p ./upload
        cp -a ./build/_deps/libzt-build/lib ./upload/
        cp -a ./build/_deps/libzt-src/include ./upload/
    - uses: actions/upload-artifact@v2
      with:
        name: libzt-win64
        path: ./upload
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
